# Generated by Django 5.1.1 on 2024-09-18 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='contact_information',
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='children',
            field=models.ManyToManyField(related_name='student_parent_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
